    if(nP.x()*bw>d0||(nP.x()+x)*bw<-d0||nP.y()*bh<-d0||(nP.y()-y)*bh>d0||nP.z()*bw>d0||(nP.z()+z)*bw<-d0){
      dZone=1; 
    }
    if(nP.x()*bw>d1||(nP.x()+x)*bw<-d1||nP.y()*bh<-d1||(nP.y()-y)*bh>d1||nP.z()*bw>d1||(nP.z()+z)*bw<-d1){
      dZone=2; 
    }
    if(nP.x()*bw>d2||(nP.x()+x)*bw<-d2||nP.y()*bh<-d2||(nP.y()-y)*bh>d2||nP.z()*bw>d2||(nP.z()+z)*bw<-d2){
      dZone=3; 
    }
    if(nP.x()*bw>d3||(nP.x()+x)*bw<-d3||nP.y()*bh<-d3||(nP.y()-y)*bh>d3||nP.z()*bw>d3||(nP.z()+z)*bw<-d3){
      dZone=4; 
    }
    if(nP.x()*bw>d4||(nP.x()+x)*bw<-d4||nP.y()*bh<-d4||(nP.y()-y)*bh>d4||nP.z()*bw>d4||(nP.z()+z)*bw<-d4){
      dZone=5; 
    }
    if(nP.x()*bw>d5||(nP.x()+x)*bw<-d5||nP.y()*bh<-d5||(nP.y()-y)*bh>d5||nP.z()*bw>d5||(nP.z()+z)*bw<-d5){
      dZone=6; 
    }
